export interface CountryOption {
  name: string
  dialCode: string
  iso2: string
}

export const COUNTRY_CODES: CountryOption[] = [
  { name: 'Kenya', dialCode: '+254', iso2: 'KE' },
  { name: 'Uganda', dialCode: '+256', iso2: 'UG' },
  { name: 'Tanzania', dialCode: '+255', iso2: 'TZ' },
  { name: 'Rwanda', dialCode: '+250', iso2: 'RW' },
  { name: 'Ethiopia', dialCode: '+251', iso2: 'ET' },
  { name: 'Nigeria', dialCode: '+234', iso2: 'NG' },
  { name: 'Ghana', dialCode: '+233', iso2: 'GH' },
  { name: 'South Africa', dialCode: '+27', iso2: 'ZA' },
  { name: 'Egypt', dialCode: '+20', iso2: 'EG' },
  { name: 'Morocco', dialCode: '+212', iso2: 'MA' },
  { name: 'United States', dialCode: '+1', iso2: 'US' },
  { name: 'Canada', dialCode: '+1', iso2: 'CA' },
  { name: 'United Kingdom', dialCode: '+44', iso2: 'GB' },
  { name: 'Ireland', dialCode: '+353', iso2: 'IE' },
  { name: 'Germany', dialCode: '+49', iso2: 'DE' },
  { name: 'France', dialCode: '+33', iso2: 'FR' },
  { name: 'Spain', dialCode: '+34', iso2: 'ES' },
  { name: 'Italy', dialCode: '+39', iso2: 'IT' },
  { name: 'Netherlands', dialCode: '+31', iso2: 'NL' },
  { name: 'Belgium', dialCode: '+32', iso2: 'BE' },
  { name: 'Switzerland', dialCode: '+41', iso2: 'CH' },
  { name: 'Sweden', dialCode: '+46', iso2: 'SE' },
  { name: 'Norway', dialCode: '+47', iso2: 'NO' },
  { name: 'Denmark', dialCode: '+45', iso2: 'DK' },
  { name: 'Poland', dialCode: '+48', iso2: 'PL' },
  { name: 'Portugal', dialCode: '+351', iso2: 'PT' },
  { name: 'Greece', dialCode: '+30', iso2: 'GR' },
  { name: 'Turkey', dialCode: '+90', iso2: 'TR' },
  { name: 'Russia', dialCode: '+7', iso2: 'RU' },
  { name: 'United Arab Emirates', dialCode: '+971', iso2: 'AE' },
  { name: 'Saudi Arabia', dialCode: '+966', iso2: 'SA' },
  { name: 'Qatar', dialCode: '+974', iso2: 'QA' },
  { name: 'India', dialCode: '+91', iso2: 'IN' },
  { name: 'Pakistan', dialCode: '+92', iso2: 'PK' },
  { name: 'Bangladesh', dialCode: '+880', iso2: 'BD' },
  { name: 'China', dialCode: '+86', iso2: 'CN' },
  { name: 'Japan', dialCode: '+81', iso2: 'JP' },
  { name: 'South Korea', dialCode: '+82', iso2: 'KR' },
  { name: 'Philippines', dialCode: '+63', iso2: 'PH' },
  { name: 'Indonesia', dialCode: '+62', iso2: 'ID' },
  { name: 'Malaysia', dialCode: '+60', iso2: 'MY' },
  { name: 'Singapore', dialCode: '+65', iso2: 'SG' },
  { name: 'Thailand', dialCode: '+66', iso2: 'TH' },
  { name: 'Vietnam', dialCode: '+84', iso2: 'VN' },
  { name: 'Australia', dialCode: '+61', iso2: 'AU' },
  { name: 'New Zealand', dialCode: '+64', iso2: 'NZ' },
  { name: 'Brazil', dialCode: '+55', iso2: 'BR' },
  { name: 'Mexico', dialCode: '+52', iso2: 'MX' },
  { name: 'Argentina', dialCode: '+54', iso2: 'AR' },
  { name: 'Colombia', dialCode: '+57', iso2: 'CO' },
  { name: 'Chile', dialCode: '+56', iso2: 'CL' },
  { name: 'Zambia', dialCode: '+260', iso2: 'ZM' },
  { name: 'Zimbabwe', dialCode: '+263', iso2: 'ZW' },
  { name: 'Malawi', dialCode: '+265', iso2: 'MW' },
  { name: 'Mozambique', dialCode: '+258', iso2: 'MZ' },
  { name: 'Somalia', dialCode: '+252', iso2: 'SO' },
  { name: 'South Sudan', dialCode: '+211', iso2: 'SS' },
  { name: 'Sudan', dialCode: '+249', iso2: 'SD' },
  { name: 'Burundi', dialCode: '+257', iso2: 'BI' },
  { name: 'Democratic Republic of Congo', dialCode: '+243', iso2: 'CD' },
  { name: 'Senegal', dialCode: '+221', iso2: 'SN' },
  { name: "Côte d'Ivoire", dialCode: '+225', iso2: 'CI' },
  { name: 'Cameroon', dialCode: '+237', iso2: 'CM' },
]
